### ISSUE TITLE
Feelings

### ISSUE THREAD

**Issue by szepeviktor** [timothyjensen/organize-admin-notices#1]
What a fantastic anti-mess idea and execution! :)
Very well done in Screen Options.

btw I have a solution for persistent notices. https://github.com/szepeviktor/wordpress-persistent-admin-notices

**Comment by timothyjensen** [comment]
Thanks for the feedback! 

Your persistent admin notices package looks useful too. I'm hopeful, though, that the [WP Notify project](https://make.wordpress.org/core/2019/08/05/feature-project-proposal-wp-notify/) will eventually be a full replacement for all our admin notice workarounds :).
