### ISSUE TITLE
Google SIte Kit screens get hidden

### ISSUE THREAD

**Issue by alvarogois** [timothyjensen/organize-admin-notices#2]
Really love this solution. Great idea and it works like a charm.

But today I was testing Google Site Kit and found that its screens get hidden by Organize Admin Notices. Is it GSK using the wrong hook to show screens or…?

Thanks.

**Comment by timothyjensen** [comment]
Thanks for reporting the issue @alvarogois. Google Site Kit apparently tries to remove all admin notices output on their admin settings screens, which was breaking the HTML rendered by this plugin. I just pushed [a fix](https://github.com/timothyjensen/organize-admin-notices/commit/6c69bc0f008c016fd756acd708e2d7ace384ee02), which you can download [here](https://github.com/timothyjensen/organize-admin-notices/archive/bugfix/unclosed-wrapper.zip). Please test it out and let me know if that solves the issue for you.

**Comment by alvarogois** [comment]
Awesome. Thanks.
